### ISSUE TITLE
Decreases in PVL causes Exception on `None.get`

### ISSUE THREAD

**Issue by ArmborstL** [utwente-fmt/vercors#1019]
The following PVL program traverses a linked list, and uses a decreases:
```
class Node {
  Node next;

  resource state() = Perm(next, write) ** (next != null ==> next.state());

  requires state();
  boolean cyclic() {
    Node last = this;
    int len = 10;

    loop_invariant last != null ==> last.state();
    decreases len;
    while(last != null) {
      unfold last.state();
      last = last.next;
      len = len-1;
    }

    return false;
  }
}
```
Running this, I get a `java.util.NoSuchElementException: None.get`.

<details><summary>Stack trace</summary>

```
Exception in thread "main" java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:627)
        at scala.None$.get(Option.scala:626)
        at viper.api.backend.SilverBackend.processError(SilverBackend.scala:230)
        at viper.api.backend.SilverBackend.processError$(SilverBackend.scala:122)
        at viper.api.backend.silicon.Silicon.processError(Silicon.scala:41)
        at viper.api.backend.SilverBackend.$anonfun$submit$9(SilverBackend.scala:113)
        at viper.api.backend.SilverBackend.$anonfun$submit$9$adapted(SilverBackend.scala:113)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at viper.api.backend.SilverBackend.submit(SilverBackend.scala:113)
        at viper.api.backend.SilverBackend.submit$(SilverBackend.scala:59)
        at viper.api.backend.silicon.Silicon.submit(Silicon.scala:41)
        at vct.main.stages.SilverBackend.verify(Backend.scala:119)
        at vct.main.stages.Backend.$anonfun$run$3(Backend.scala:108)
        at vct.main.stages.Backend.$anonfun$cachedDefinitelyVerifiesOrElseUpdate$1(Backend.scala:74)
        at scala.Option.getOrElse(Option.scala:201)
        at vct.main.stages.Backend.cachedDefinitelyVerifiesOrElseUpdate(Backend.scala:72)
        at vct.main.stages.Backend.cachedDefinitelyVerifiesOrElseUpdate$(Backend.scala:71)
        at vct.main.stages.SilverBackend.cachedDefinitelyVerifiesOrElseUpdate(Backend.scala:117)
        at vct.main.stages.Backend.$anonfun$run$2(Backend.scala:108)
        at vct.main.stages.Backend.$anonfun$run$2$adapted(Backend.scala:107)
        at hre.progress.Progress$.$anonfun$foreach$2(Progress.scala:78)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at hre.progress.task.AbstractTask.frame(AbstractTask.scala:142)
        at hre.progress.Progress$.$anonfun$foreach$1(Progress.scala:78)
        at hre.progress.Progress$.$anonfun$foreach$1$adapted(Progress.scala:76)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1288)
        at hre.progress.Progress$.foreach(Progress.scala:76)
        at vct.main.stages.Backend.run(Backend.scala:107)
        at vct.main.stages.Backend.run$(Backend.scala:106)
        at vct.main.stages.SilverBackend.run(Backend.scala:117)
        at vct.main.stages.SilverBackend.run(Backend.scala:117)
        at hre.stages.UnitStages.runUnsafely(Stages.scala:48)
        at hre.stages.StagesPair.runUnsafely(Stages.scala:56)
        at hre.stages.StagesPair.runUnsafely(Stages.scala:54)
        at hre.stages.Stages.$anonfun$run$1(Stages.scala:30)
        at hre.progress.task.NameSequenceTask.scope(NameSequenceTask.scala:12)
        at hre.progress.Progress$.stages(Progress.scala:101)
        at hre.stages.Stages.run(Stages.scala:29)
        at hre.stages.Stages.run$(Stages.scala:27)
        at hre.stages.StagesPair.run(Stages.scala:52)
        at vct.main.modes.Verify$.verifyWithOptions(Verify.scala:46)
        at vct.main.modes.Verify$.runOptions(Verify.scala:74)
        at vct.main.Main$.runOptions(Main.scala:88)
        at vct.main.Main$.main(Main.scala:41)
        at vct.main.Main.main(Main.scala)
```

</details>

Note that in this reduced example, the `decreases` clause is not actually guaranteed to be non-negative, and should raise an error. 

Loading the generated backend file into Viper, it reports `Assert might fail. Assertion true && last != null ==> (decreasing(len, old_W1_T0): Bool) && (bounded(old_W1_T0): Bool) || len == old_W1_T0 && false might not hold. (<no position>)`
It might be that lack of position that causes the exception in the translation of the error in VerCors.

**Comment by superaxander** [comment]
This is working now. I think it's worked since 36c700d03e55a4c2af6b5736503bf5bb9027d0d2
