### ISSUE TITLE
"Cannot invoke "java.io.InputStream.close()" because "vct.main.BuildInfo$.buildInfoInputStream" is null"

### ISSUE THREAD

**Issue by Drevanoorschot** [utwente-fmt/vercors#1038]
After a git checkout, my build started acting weird and I couldn't solve it. Therefore i decided to reclone and rebuild the vercors project. The build does not generate any errors except when i run VerCors i get the following error and trace:
```
20:40:26.751 [main] ERROR vct.main.Main$ - Unrecoverable error: null
java.lang.ExceptionInInitializerError: null
	at vct.options.Options$.constructParser(Options.scala:48)
	at vct.options.Options$.parser(Options.scala:18)
	at vct.options.Options$.parse(Options.scala:301)
	at vct.main.Main$.main(Main.scala:39)
	at vct.main.Main.main(Main.scala)
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.close()" because "vct.main.BuildInfo$.buildInfoInputStream" is null
	at vct.main.BuildInfo$.<clinit>(BuildInfo.scala:12)
	... 5 common frames omitted
Exception in thread "main" java.lang.ExceptionInInitializerError
	at vct.options.Options$.constructParser(Options.scala:48)
	at vct.options.Options$.parser(Options.scala:18)
	at vct.options.Options$.parse(Options.scala:301)
	at vct.main.Main$.main(Main.scala:39)
	at vct.main.Main.main(Main.scala)
Caused by: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.close()" because "vct.main.BuildInfo$.buildInfoInputStream" is null
	at vct.main.BuildInfo$.<clinit>(BuildInfo.scala:12)
	... 5 more
	```
I've tried to rebuild the project, and resync BSP in Intellij but unfortunately the error remains.

**Comment by niomaster** [comment]
Hmm, I can't reproduce this from a fresh build. It seems somehow `BuildInfo.buildinfo.properties` is not on your classpath. Could you post the output of:

```
$ ./mill path vercors.run vercors.buildInfo.buildInfoResources
```

Which should output:

```
$ ./mill path vercors.run vercors.buildInfo.buildInfoResources
[1/1] path 
vercors.buildInfo.buildInfoResources
vercors.buildInfo.resources
vercors.buildInfo.localClasspath
vercors.transitiveLocalPackedClasspath
vercors.upstreamAssemblyClasspath
vercors.runClasspath
vercors.run
```

Also, `./mill show vercors.runClasspath` should in fact include `out/vercors/buildInfo/buildInfoResources.dest`, does it?
