### ISSUE TITLE
Backend crash when using `--assumeInjectivityOnInhale`

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#1045]
Given the following program:

```
class C {
  int f;
}

context cs != null ** Perm(cs[*], 1);
ensures (\forall* int i = 0 .. cs.length; Perm(cs[i].f, 1));
void m(C[] cs) {

}
```

If you analyze this with the `--assumeInjectivityOnInhale` flag, a crash occurs:

```
$ ~/Workbench/Projects/vercors_dev/bin/vct inj_repro.pvl --backend-option --assumeInjectivityOnInhale
[581/623] vercors.buildInfo.resources
[INFO] Starting verification
[ERROR] Unrecoverable error: Quantified resource aloc(opt_get1(cs), i).ref.f might not be injective. (of class viper.silver.verifier.reasons$QPAssertionNotInjective)
scala.MatchError: Quantified resource aloc(opt_get1(cs), i).ref.f might not be injective. (of class viper.silver.verifier.reasons$QPAssertionNotInjective)
        at viper.api.backend.SilverBackend.getFailure(SilverBackend.scala:283)
        at viper.api.backend.SilverBackend.getFailure$(SilverBackend.scala:283)
        at viper.api.backend.silicon.Silicon.getFailure(Silicon.scala:41)
        at viper.api.backend.SilverBackend.processError(SilverBackend.scala:184)
        at viper.api.backend.SilverBackend.processError$(SilverBackend.scala:122)
        at viper.api.backend.silicon.Silicon.processError(Silicon.scala:41)
        at viper.api.backend.SilverBackend.$anonfun$submit$9(SilverBackend.scala:113)
        at viper.api.backend.SilverBackend.$anonfun$submit$9$adapted(SilverBackend.scala:113)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at viper.api.backend.SilverBackend.submit(SilverBackend.scala:113)
        at viper.api.backend.SilverBackend.submit$(SilverBackend.scala:59)
        at viper.api.backend.silicon.Silicon.submit(Silicon.scala:41)
        at vct.main.stages.SilverBackend.verify(Backend.scala:119)
        ...
```

Analysing the backend viper file with `bin/silicon` just gives a plain error about the failing injectivity in the postcondition, so I suspect it's some edge case that's properly handled in silicon, but not in the API that we're using somehow. Without the `--assumeInjectivityOnInhale` VerCors does give a proper error message.

I know we don't officially support problems through use of `--backend-option`, but I think this one would be good to fix nevertheless. Anyhow I'll try to debug it for a bit.

**Comment by pieter-bos** [comment]
Indeed this is not supported, and a case where `--backend-option` is not always safe. The assumption that injectivity is a wf condition is pretty baked in now, so I'd have to look around a bit where it needs to change. Your PR is certainly not complete, for lots of errors we filter by reason to distinguish failures with a reason and well-formedness failures.

**Comment by pieter-bos** [comment]
That said I'm not opposed to changing it :). In fact I think we should consider switching back to `--assumeInjectivityOnInhale` by default.

**Comment by bobismijnnaam** [comment]
It's not really clear to me what the tradeoff is there, but it's probably for the best.
