### ISSUE TITLE
Verifying without --no-infer-heap-context-into-frame sometimes throws an error

### ISSUE THREAD

**Issue by Ellen-Wittingen** [utwente-fmt/vercors#1101]
For some files, such as `examples/concepts/sycl/accessors/GetKernelResult.cpp` on the [sycl-rq3](https://github.com/utwente-fmt/vercors/tree/sycl-rq3) branch, the verification throws an error when `--no-infer-heap-context-into-frame` is NOT enabled:
```
#include <sycl/sycl.hpp>

/*@ 
  requires \pointer(a, 10, write);
*/
void main(int* a) {
	sycl::queue myQueue;

  {
    sycl::buffer<int, 1> aBuffer = sycl::buffer(a, sycl::range<1>(10));

    myQueue.submit(
      [&](sycl::handler& cgh) {
        
        sycl::accessor<int, 1> a_accessor = sycl::accessor(aBuffer, cgh, sycl::read_write);

        cgh.parallel_for(sycl::range<1>(10),
          /*@
            context it.get_id(0) < a_accessor.get_range().get(0);
            context Perm(a_accessor[it.get_id(0)], write);
            ensures a_accessor[it.get_id(0)] == 10;
          */
          [=] (sycl::item<1> it) {
            a_accessor[it.get_id(0)] = 10;
          }
        );
      }
    );
  } // Leaving scope, so automatically wait on all running kernels to finish and write data back to the buffers

  //@ assert (\forall int i; i >= 0 && i < 10; a[i] == 10);

}
```
The following error is thrown:
```
vct.col.origin.BlameUnreachable: An error condition was reached, which should be statically unreachable. schematic. Inner failure:
 > ======================================
 > 32  
 >    33  }
 >       [
 >    34  
 >        ]
 > --------------------------------------
 > There may be insufficient permission to access this field here. (https://utwente.nl/vercors#perm)
 > ======================================
	at vct.col.origin.PanicBlame.blame(Blame.scala:805)
	at viper.api.backend.SilverBackend.defer(SilverBackend.scala:313)
	at viper.api.backend.SilverBackend.defer$(SilverBackend.scala:307)
	at viper.api.backend.silicon.Silicon.defer(Silicon.scala:41)
	at viper.api.backend.SilverBackend.processError(SilverBackend.scala:142)
	at viper.api.backend.SilverBackend.processError$(SilverBackend.scala:123)
	at viper.api.backend.silicon.Silicon.processError(Silicon.scala:41)
	at viper.api.backend.SilverBackend.$anonfun$submit$9(SilverBackend.scala:113)
	at viper.api.backend.SilverBackend.$anonfun$submit$9$adapted(SilverBackend.scala:113)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at viper.api.backend.SilverBackend.submit(SilverBackend.scala:113)
	at viper.api.backend.SilverBackend.submit$(SilverBackend.scala:59)
	at viper.api.backend.silicon.Silicon.submit(Silicon.scala:41)
	at vct.main.stages.SilverBackend.verify(Backend.scala:119)
	at vct.main.stages.Backend.$anonfun$run$3(Backend.scala:108)
	at vct.main.stages.Backend.$anonfun$cachedDefinitelyVerifiesOrElseUpdate$1(Backend.scala:74)
	at scala.Option.getOrElse(Option.scala:201)
	at vct.main.stages.Backend.cachedDefinitelyVerifiesOrElseUpdate(Backend.scala:72)
	at vct.main.stages.Backend.cachedDefinitelyVerifiesOrElseUpdate$(Backend.scala:71)
	at vct.main.stages.SilverBackend.cachedDefinitelyVerifiesOrElseUpdate(Backend.scala:117)
	at vct.main.stages.Backend.$anonfun$run$2(Backend.scala:108)
	at vct.main.stages.Backend.$anonfun$run$2$adapted(Backend.scala:107)
	at hre.progress.Progress$.$anonfun$foreach$2(Progress.scala:77)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at hre.progress.task.AbstractTask.frame(AbstractTask.scala:142)
	at hre.progress.Progress$.$anonfun$foreach$1(Progress.scala:77)
	at hre.progress.Progress$.$anonfun$foreach$1$adapted(Progress.scala:75)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1288)
	at hre.progress.Progress$.foreach(Progress.scala:75)
	at vct.main.stages.Backend.run(Backend.scala:107)
	at vct.main.stages.Backend.run$(Backend.scala:106)
	at vct.main.stages.SilverBackend.run(Backend.scala:117)
	at vct.main.stages.SilverBackend.run(Backend.scala:117)
	at hre.stages.UnitStages.runUnsafely(Stages.scala:48)
	at hre.stages.StagesPair.runUnsafely(Stages.scala:56)
	at hre.stages.StagesPair.runUnsafely(Stages.scala:54)
	at hre.stages.Stages.$anonfun$run$1(Stages.scala:30)
	at hre.progress.task.NameSequenceTask.scope(NameSequenceTask.scala:12)
	at hre.progress.Progress$.stages(Progress.scala:100)
	at hre.stages.Stages.run(Stages.scala:29)
	at hre.stages.Stages.run$(Stages.scala:27)
	at hre.stages.StagesPair.run(Stages.scala:52)
	at vct.main.modes.Verify$.verifyWithOptions(Verify.scala:46)
	at vct.main.modes.Verify$.runOptions(Verify.scala:74)
	at vct.main.Main$.runOptions(Main.scala:88)
	at vct.main.Main$.main(Main.scala:41)
	at vct.main.Main.main(Main.scala)
```
When checking the difference between the generated Viper code between using the flag and not using it, the one without the flag has the following extra Viper code:
```
 [(forperm
   obj: Ref [obj.bool] :: obj.bool == old[beforeFrame](obj.bool)) &&
(forperm
  obj: Ref [obj.int] :: obj.int == old[beforeFrame](obj.int)) &&
(forperm
  obj: Ref [obj.rat] :: obj.rat == old[beforeFrame](obj.rat)) &&
(forperm
  obj: Ref [obj.int1] :: obj.int1 == old[beforeFrame](obj.int1)) &&
(forperm
  obj: Ref [obj.a_accessor] :: obj.a_accessor ==
  old[beforeFrame](obj.a_accessor)) &&
(forperm
  obj: Ref [obj.a_accessor_dim] :: obj.a_accessor_dim ==
  old[beforeFrame](obj.a_accessor_dim)),
true]
```
So my guess is that the error is probably thrown because of something in that extra generated code.

I have not seen this happen outside of the [sycl-rq3](https://github.com/utwente-fmt/vercors/tree/sycl-rq3) branch.

**Comment by pieter-bos** [comment]
It seems this example doesn't parse on the `sycl-rq3` branch currently, could you post the full viper file?

**Comment by pieter-bos** [comment]
My current hypothesis is this:

```
field f: Int

method test(x: Ref)
{
    var once: Bool := true

    label beforeFrame

    while(once)
    invariant once ==> acc(x.f, 1/4)
    invariant once ==> [(forperm obj: Ref [obj.f] :: obj.f == old[beforeFrame](obj.f)), true]
    {
        once := false
    }
}
```

Indeed, within the old there is insufficient permission to read `obj.f`, since the method requires no permission at all. VerCors incorrectly assumes that viper would report that the invariant cannot be established, even before its well-formedness is checked.

This would only happen if there is insufficient permission outside a `FramedProof` (e.g. parallel blocks are encoded to that) to establish it, so I don't understand how it would then verify with `--no-infer-heap-context-into-frame`

**Comment by Ellen-Wittingen** [comment]
Hmm, the example parses for me just fine, weird (it does take about 2 minutes).

Here is the full Viper file without `--no-infer-heap-context-into-frame`:
[vprtest-0.txt](https://github.com/utwente-fmt/vercors/files/13264746/vprtest-0.txt)

And the full Viper file with `--no-infer-heap-context-into-frame` enabled:
[vprtest-1.txt](https://github.com/utwente-fmt/vercors/files/13264797/vprtest-1.txt)

**Comment by pieter-bos** [comment]
<details><summary>Reduced</summary>

```
domain Array {
    function loc(a: Array, i: Int): Ref
    function loc_inv_1(x: Ref): Array
    function loc_inv_2(x: Ref): Int

    axiom { forall a: Array, i: Int :: {loc(a, i)} loc_inv_1(loc(a, i)) == a }
    axiom { forall a: Array, i: Int :: {loc(a, i)} loc_inv_2(loc(a, i)) == i }
}

field len: Int
field arr_int: Int

method test(x: Ref, a: Array)
requires acc(x.len, wildcard)
requires forall i: Int :: 0 <= i && i < x.len ==> acc(loc(a, i).arr_int, write)
{
    var once: Bool := true

    label before

    while(once)
    invariant once ==> (
        acc(x.len, wildcard) &&
        forall i: Int :: 0 <= i && i < x.len ==> acc(loc(a, i).arr_int, write)
    )
    invariant once ==> (
        [
        (forperm o: Ref [o.arr_int] :: o.arr_int == old[before](o.arr_int)) &&
        (forperm o: Ref [o.len] :: o.len == old[before](o.len))
        ,
        true
        ]
    )

    invariant !once ==> (
        true
    )
    {
        once := false
    }
}
```
</details>

Reports:

```
Contract might not be well-formed. There might be insufficient permission to access o.arr_int (frame-forperm-order.vpr@26.15--33.6)
```

Note that the example does pass if the order of the `forperm`s is swapped. The reason is as follows. In the maintain proof of the loop invariant, the loop invariant is inhaled from a fresh heap. At that time we have no knowledge of the heap values of `len` and `arr_int`. The auto-generated `forperm`s help with exactly that: they state that the heap values at the start of the loop iteration are the same as they were at the label `before`. Heap-dependent expressions under an `old` are evaluated in the specified old heap. Consequentially they have to be well-defined in the old heap. At first sight it seemed to me like this should always be the case, since the loop invariant is necessarily a smaller heap than the one at `before` (otherwise, how could we have entered the loop). However, since the loop body is verified in a fresh heap, we don't know yet that `x.len` is in fact the same as `old[before](x.len)` at the time we are assuming the `arr_int` values for which we have permission are the same. We must assume that we may have permission for `loc(a, i).arr_int` for an `i` `old[before](x.len) <= i < x.len`, and we do not have permission for such locations at the `before` label. It's only after we assume that all `len` values are the same that we know there is no such `i`.

Another view of this is that the assertion `forall i: Int :: 0 <= i && i < x.len ==> acc(loc(a, i).arr_int, write)` potentially has a different meaning before the loop and in the loop, because `x.len` is not constant. I think a part of the solution here is to analyse the places in which dereferences occur in the `Frame` contract and order the `ForPerm` assertions according to that. Some things to think about still:

- [ ] Can we construct an example that still won't work using `unfolding`?
- [ ] What about the issue above, is it safe enough after solving this to report `forperm` well-formedness problems as failing the precondition of the frame?
