### ISSUE TITLE
Subscript blame reported on wrong node

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#1123]
I think the blame for subscript out of bounds indexing is reported on the wrong node somehow. The following program:

```
void initu(int i) {
  int[] u = null;
  u[i] = 1;
}
```

Causes the following output:

```
[INFO] Starting verification
vct.col.origin.BlameUnreachable: An error condition was reached, which should be statically unreachable. Assigning to a subscript should trigger an error on the assignment, and not on the subscript.. Inner failure:
 > ======================================
 > At test.pvl
 > --------------------------------------
 >     1  void initu(int i) {
 >     2    int[] u = null;
 >         [-
 >     3    u[i] = 1;
 >          -]
 >     4  }
 >     5
 > --------------------------------------
 > Array may be null. (https://utwente.nl/vercors#arrayNull)
 > ======================================
        at vct.col.origin.PanicBlame.blame(Blame.scala:915)
        at vct.col.rewrite.adt.ImportArray$ArrayNullOptNone.blame(ImportArray.scala:23)
        at vct.col.rewrite.adt.ImportArray$ArrayNullOptNone.blame(ImportArray.scala:21)
        at vct.col.rewrite.adt.ImportOption$OptionNonePreconditionFailed.blame(ImportOption.scala:10)
        at vct.col.rewrite.adt.ImportOption$OptionNonePreconditionFailed.blame(ImportOption.scala:8)
        at vct.col.origin.NoContext.blame(Blame.scala:961)
        at vct.col.origin.NoContext.blame(Blame.scala:959)
        at viper.api.backend.SilverBackend.processError(SilverBackend.scala:148)
        at viper.api.backend.SilverBackend.processError$(SilverBackend.scala:123)
        at viper.api.backend.silicon.Silicon.processError(Silicon.scala:42)
        at viper.api.backend.SilverBackend.$anonfun$submit$9(SilverBackend.scala:113)
        at viper.api.backend.SilverBackend.$anonfun$submit$9$adapted(SilverBackend.scala:113)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at viper.api.backend.SilverBackend.submit(SilverBackend.scala:113)
        at viper.api.backend.SilverBackend.submit$(SilverBackend.scala:59)
        at viper.api.backend.silicon.Silicon.submit(Silicon.scala:42)
        at vct.main.stages.SilverBackend.verify(Backend.scala:119)
        at vct.main.stages.Backend.$anonfun$run$3(Backend.scala:108)
        at vct.main.stages.Backend.$anonfun$cachedDefinitelyVerifiesOrElseUpdate$1(Backend.scala:74)
        at scala.Option.getOrElse(Option.scala:201)
        at vct.main.stages.Backend.cachedDefinitelyVerifiesOrElseUpdate(Backend.scala:72)
        at vct.main.stages.Backend.cachedDefinitelyVerifiesOrElseUpdate$(Backend.scala:71)
        at vct.main.stages.SilverBackend.cachedDefinitelyVerifiesOrElseUpdate(Backend.scala:117)
        at vct.main.stages.Backend.$anonfun$run$2(Backend.scala:108)
        at vct.main.stages.Backend.$anonfun$run$2$adapted(Backend.scala:107)
        at hre.progress.Progress$.$anonfun$foreach$2(Progress.scala:77)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at hre.progress.task.AbstractTask.frame(AbstractTask.scala:142)
        at hre.progress.Progress$.$anonfun$foreach$1(Progress.scala:77)
        at hre.progress.Progress$.$anonfun$foreach$1$adapted(Progress.scala:75)
        at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
        at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1288)
        at hre.progress.Progress$.foreach(Progress.scala:75)
        at vct.main.stages.Backend.run(Backend.scala:107)
        at vct.main.stages.Backend.run$(Backend.scala:106)
        at vct.main.stages.SilverBackend.run(Backend.scala:117)
        at vct.main.stages.SilverBackend.run(Backend.scala:117)
        at hre.stages.UnitStages.runUnsafely(Stages.scala:48)
        at hre.stages.StagesPair.runUnsafely(Stages.scala:56)
        at hre.stages.StagesPair.runUnsafely(Stages.scala:54)
        at hre.stages.Stages.$anonfun$run$1(Stages.scala:30)
        at hre.progress.task.NameSequenceTask.scope(NameSequenceTask.scala:12)
        at hre.progress.Progress$.stages(Progress.scala:100)
        at hre.stages.Stages.run(Stages.scala:29)
        at hre.stages.Stages.run$(Stages.scala:27)
        at hre.stages.StagesPair.run(Stages.scala:52)
        at vct.main.modes.Verify$.verifyWithOptions(Verify.scala:46)
        at vct.main.modes.Verify$.runOptions(Verify.scala:74)
        at vct.main.Main$.runOptions(Main.scala:88)
        at vct.main.Main$.main(Main.scala:41)
        at vct.main.Main.main(Main.scala)
```

EDIT: Actually, I meant this program, which gives the index negative/out of bounds error:

```
requires n >= 0;
void initu(int i, int n) {
  int[] u = new int[n];
  u[i] = 1;
}
```

But I guess in both cases the error shouldn't be a panicblame.

**Comment by bobismijnnaam** [comment]
Ran into this again the other day!

```
requires a != null ** a.length == 0;
void m(int[] a) {
  a[0] = 3;
}
```
