### ISSUE TITLE
Giving a frac to the array predicate yields IndexOutOfBoundsException

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#216]
When I give a frac to an \array vercors seems to crash. The program:
```
class myclass {
  requires \array(xs, p);
  void foo(int[] xs, frac p) { }
}
```
The output:
```
Plain foo
Parsed 1 file(s) in: 171ms
WARNING: missing origin
java.lang.IndexOutOfBoundsException: 0
        at scala.collection.LinearSeqOptimized.apply(LinearSeqOptimized.scala:63)
        at scala.collection.LinearSeqOptimized.apply$(LinearSeqOptimized.scala:61)
        at scala.collection.immutable.List.apply(List.scala:85)
        at vct.col.ast.Type.firstarg(Type.scala:29)
        at vct.col.rewrite.SilverClassReduction.rewriteAll(SilverClassReduction.java:594)
        at vct.main.Main$48.apply(Main.java:956)
        at vct.main.CompilerPass.apply(CompilerPass.java:29)
        at vct.main.CompilerPass.apply_pass(CompilerPass.java:24)
        at vct.main.Main.main(Main.java:553)
entire run took 2185 ms
```
I would expect something like "\array does not support fractions".

**Comment by niomaster** [comment]
There is a missing force_frac in the type check of ValidArray

**Comment by niomaster** [comment]
Actually `\array` takes a length, i.e. integer as a second argument. For `Perm` and so on this now works fine.
