### ISSUE TITLE
hre.lang.HREError: primitive type Resource unsupported

### ISSUE THREAD

**Issue by sjcjoosten** [utwente-fmt/vercors#267]
I was asked to report the following:

```
[progress] [98%] check took 1160 ms
[progress] Applying silver ...
[progress] verifying with builtin silicon backend
[debug] At Main.java:634: 
[debug] hre.lang.HREError: primitive type Resource unsupported
[debug] At Main.java:634: 
[debug] 	at vct.silver.SilverTypeMap.map(SilverTypeMap.java:107)
[debug] At Main.java:634: 
[debug] 	at vct.col.ast.type.PrimitiveType.accept_simple(PrimitiveType.java:116)
[debug] At Main.java:634: 
[debug] 	at vct.col.ast.type.Type.apply(Type.scala:60)
[debug] At Main.java:634: 
[debug] 	at vct.silver.VerCorsProgramFactory.split_block(VerCorsProgramFactory.java:344)
[debug] At Main.java:634: 
[debug] 	at vct.silver.VerCorsProgramFactory.convert(VerCorsProgramFactory.java:215)
[debug] At Main.java:634: 
[debug] 	at vct.silver.VerCorsProgramFactory.convert(VerCorsProgramFactory.java:36)
[debug] At Main.java:634: 
[debug] 	at vct.silver.SilverBackend.TestSilicon(SilverBackend.java:132)
[debug] At Main.java:634: 
[debug] 	at vct.main.Main$9.apply_pass(Main.java:704)
[debug] At Main.java:634: 
[debug] 	at vct.main.Main.main(Main.java:603)
[debug] At Main.java:635:
An unexpected error occured in VerCors! Please report an issue at https://github.com/utwente-fmt/vercors/issues/new. You can see the full exception by adding '--debug vct.main.Main' to the flags.
[debug] At Main.java:638:
The final verdict is Error
[progress] entire run took 56617 ms
```

The culprit is probably this line (in Java code):
```
				prove_safe_disregard( current.right, node, to_bag_except(current.right, node), get_color(current.right, node)
				                    , \old(\unfolding tree_perm_except(current,node) \in blackHeight(node, null, 0)));
```

I ran this using:
```
time /Users/sjc/Documents/Twente/VerCors/vercors/unix/bin/vct --silicon src/Node.java src/Tree.java
```
[Archive.zip](https://github.com/utwente-fmt/vercors/files/3491279/Archive.zip)

Help is wanted in trying to minimise the example. I'd of course like for this to work, but a better error message might also be a way of fixing this bug.

**Comment by niomaster** [comment]
From a smaller example:

```
final class T {
    T x; 
}

final class T2 {
    /*@ public resource tr(T t) = t != null ==> (Perm(t.x,write) ** tr(t.x));@*/
    
    
    /*@ requires t != null;@*/
    /*@ requires tr(t);@*/
    public void te(T t) {
        /*@ assert \old(\unfolding tr(t) \in (t.x==null || t.x != null));@*/
        /*@ ghost t2(\unfolding tr(t) \in t.x);@*/
    }
    
    /*@ 
    ghost public void t2(T t) {
    }
    @*/
}
```

This is generated:

```
{
  resource __flatten_1__3;
  assert \old( \unfolding ([ write ] method_T2_tr__T(diz,globals,t)) \in (t.field_T_x == null || t.field_T_x != null) );
  __flatten_1__3=[ write ] method_T2_tr__T(diz,globals,t);
  method_T2_t2__T(sys__thrown,diz,current_thread_id,globals,\unfolding __flatten_1__3 \in t.field_T_x);
}
```

The root cause is that "method invokations" are always flattened unconditionally (in reverse; i.e. they need to be at the top level of an expression). This is to support with/then correctly with respect to expression evaluation order. I don't think this should ever happen for the application of resource predicates, as we can do nothing with a resource "value".

**Comment by niomaster** [comment]
Side-effect extraction now distinguishes between pure expression contexts (i.e. resources), and places where we can emit side effects.

> as we can do nothing with a resource "value".

lol
