### ISSUE TITLE
Using fully qualified class name in new does not parse

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#354]
The following code does not parse:

```
package com.example;

class MyClass {
    void foo() {
        new com.example.MyClass();
    }
}
```

I might expect it to throw an error because the java file is just in some random directory, and not in ./com/example/MyClass.java, but instead I get a parsing error:

```
[progress] parsing inputs...
[progress] Parsing java file ./QualifiedNew.java
[progress] first parsing pass took 110ms
[warning] Exception class hre.lang.HREError while parsing ./QualifiedNew.java
[debug] At Main.java:667:
[debug] hre.lang.HREError: missing case: (createdName (javaIdentifier com) . (javaIdentifier example) . (javaIdentifier MyClass))
[debug] At Main.java:667:
[debug]         at vct.antlr4.parser.ANTLRtoCOL.MissingCase(ANTLRtoCOL.java:781)
[debug] At Main.java:667:
[debug]         at vct.antlr4.parser.Java7JMLtoCol.visitCreatedName(Java7JMLtoCol.java:696)
[debug] At Main.java:667:
[debug]         at vct.antlr4.parser.Java7JMLtoCol.visitCreatedName(Java7JMLtoCol.java:48)
```

Probably an easy fix since it's just a missing case in the parser. COL already supports qualified identifiers I think.

**Comment by niomaster** [comment]
This will all work now I think.
