### ISSUE TITLE
Assignment to class type is not properly detected

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#413]
I typed the following typo today:

```
class MyClass {
  void foo() {
    MyClass = new MyClass();
  }
}
```

VerCors could not verify this (which is what I expect), but it did give me the wrong error message:

```
[progress] [90%] silver-optimize took 100 ms
[progress] [92%] check took 10 ms
[progress] [93%] quant-optimize took 0 ms
[progress] [95%] standardize-functions took 10 ms
[progress] [96%] standardize took 0 ms
[progress] [98%] check took 10 ms
[progress] Applying silver ...
[progress] verifying with builtin silicon backend
[debug] At Main.java:676:
[debug] hre.lang.HREError: cannot map class vct.col.ast.type.ClassType to expression (file examples/classes/assign_bug.pvl from line 3 column 5 until line 3 column 11)
[debug] At Main.java:676:
[debug]         at vct.silver.SilverExpressionMap.post_map(SilverExpressionMap.java:48)
[debug] At Main.java:676:
[debug]         at vct.col.ast.generic.ASTNode.apply(ASTNode.java:190)
[debug] At Main.java:676:
[debug]         at vct.silver.SilverStatementMap.map(SilverStatementMap.java:129)
[debug] At Main.java:676:
[debug]         at vct.col.ast.expr.MethodInvokation.accept_simple(MethodInvokation.java:79)
[debug] At Main.java:676:
[debug]         at vct.col.ast.generic.ASTNode.apply(ASTNode.java:189)
[debug] At Main.java:676:
[debug]         at vct.silver.VerCorsProgramFactory.split_block(VerCorsProgramFactory.java:357)
[debug] At Main.java:676:
[debug]         at vct.silver.VerCorsProgramFactory.convert(VerCorsProgramFactory.java:218)
[debug] At Main.java:676:
[debug]         at vct.silver.VerCorsProgramFactory.convert(VerCorsProgramFactory.java:37)
[debug] At Main.java:676:
[debug]         at vct.silver.SilverBackend.TestSilicon(SilverBackend.java:81)
[debug] At Main.java:676:
[debug]         at vct.silver.SilverBackend.TestSilicon(SilverBackend.java:67)
[debug] At Main.java:676:
[debug]         at vct.main.Main$8.apply_pass(Main.java:741)
[debug] At Main.java:676:
[debug]         at vct.main.Main.main(Main.java:642)
[debug] At Main.java:677:
```

I would've expected VerCors to tell me I cannot assign to a class type, but instead we get an error saying translation to silver failed. I think the typechecking has to take into account types cannot be assigned to, as it currently doesn't seem to do this.

(Funnily enough if I change the type to "int" it aborts directly after parsing, altough it aborts with a parse error in that case. I would like it it to say there as well "cannot assign to int"...)

**Comment by niomaster** [comment]
The error is certainly wrong, but I don't think the issue lies with assining to types per se, but rather the fact that the scope for names conflicts with that of types, i.e. VerCors should not be able to find the name MyClass in this context (this is also what the java compiler reports). This for example is allowed:

```
class MyClass {
  void test() {
    Object MyClass;
    MyClass = null;
  }
}
```

As for the `int` error, I think that's just an effect of the lexer. "class type" and "name" share a lexer symbol Identifier, whereas `int` is lexed separately (and hence neither a valid name nor class type)

**Comment by niomaster** [comment]
Actually I do agree that we should check that we are not assigning to a type, though I would prefer for this to be structurally wrong, rather than by type check.

**Comment by niomaster** [comment]
Now outputs:

```
[INFO] Starting verification
[19.0%] (2/5) Name ResolutionInternal type error: CoercionErrors must not bubble. Expression PVLNew(MyClass,List(),List(),List()) (err: scala.MatchError) could not be coerced to TNotAValue() (err: scala.NotImplementedError)
======================================
At examples/private/scoping.pvl:3:15:
--------------------------------------
    1  class MyClass {
    2    void foo() {
                    [-------------
    3      MyClass = new MyClass();
                     -------------]
    4    }
    5  }
--------------------------------------
Expected the type of this expression to be `TNotAValue() (err: scala.NotImplementedError)`, but got MyClass.
======================================
```

Still not great.
