### ISSUE TITLE
Informative error message for wrong syntax in pure function

### ISSUE THREAD

**Issue by petravandenbos-utwente** [utwente-fmt/vercors#507]
I think the syntax of the following program is not correct (need to use = instead of { }, and not use if (..) { }). The error message does not indicate something like this though, it says: "An unexpected error occured in VerCors!".

class myPureError {

	pure static int myFunc() {
	  if (true) {
		  return 1;
	  }
	}
}

The debug information says "unsupported variant of if-then", so this information could be given to the VerCors user.

[debug] At Main.java:662: 
[debug] hre.lang.HREError: unsupported variant of if-then if (true) {
[debug] At Main.java:662: 
[debug]   return 1/*@ then {
[debug] At Main.java:662: 
[debug]   } */;
[debug] At Main.java:662: 
[debug] }
[debug] At Main.java:662: 
[debug] 	at vct.col.rewrite.PureMethodsAsFunctions.do_body(PureMethodsAsFunctions.java:68)
[debug] At Main.java:662: 
[debug] 	at vct.col.rewrite.PureMethodsAsFunctions.visit(PureMethodsAsFunctions.java:33)
[debug] At Main.java:662: 
[debug] 	at vct.col.ast.stmt.decl.Method.accept_simple(Method.java:216)
[debug] At Main.java:662: 
[debug] 	at vct.col.ast.generic.ASTNode.accept(ASTNode.java:178)
[debug] At Main.java:662: 
[debug] 	at vct.col.ast.generic.ASTNode.apply(ASTNode.java:227)
[debug] At Main.java:662: 
[debug] 	at vct.col.ast.util.AbstractRewriter.rewrite(AbstractRewriter.java:234)
[debug] At Main.java:662: 
[debug] 	at vct.col.ast.util.AbstractRewriter.rewriteAll(AbstractRewriter.java:554)
[debug] At Main.java:662: 
[debug] 	at vct.main.Main$38.apply(Main.java:952)
[debug] At Main.java:662: 
[debug] 	at vct.main.CompilerPass.apply(CompilerPass.java:29)
[debug] At Main.java:662: 
[debug] 	at vct.main.CompilerPass.apply_pass(CompilerPass.java:24)
[debug] At Main.java:662: 
[debug] 	at vct.main.Main.main(Main.java:619)
[debug] At Main.java:663:

**Comment by niomaster** [comment]
This comes from a feature that attempts to encode normal methods with the "pure" attribute to functions. The list of transformations it supports is:

- Assertions, these are ignored (??)
- Unfold, encoded as unfolding (p) in (further method body)
- If statements, having exactly one if body and one else body (so in practice the else body is missing here)
- Return, which is just encoded as the return value of the function

I would argue that this is not useful enough to continue supporting it and I propose we disallow marking methods as pure for this reason.

**Comment by bobismijnnaam** [comment]
I'm not sure I agree. From what I've seen the transformation is not too complicated, and adding error messages for the missing parts (or the mandatory else branch, for that matter) is doable. (Random thought: maybe we can encode assertions through generating an identity function with the assertion as precondition, but that's for later) Also, at least one of the tests in the suite uses it I think, so there is a small reason to keep it. Do you have a particular reason for wanting to remove it @niomaster?

Of course keeping it entails documenting it properly, as the semantics of `pure` are quite vague at the moment. I don't mind doing that (unless someone already took care of it in the tutorial). In the short term we can maybe add a user-friendly error for missing else branches and error on assertions.

Final thought: we should probably also error on post-conditions with permissions on pure methods if we keep it.

**Comment by niomaster** [comment]
No, I don't have a particular reason to remove it. It's mostly that I don't think it's a very useful feature, but if you as a user think it's a useful feature we should keep it :). It's more about the cost of supporting a feature used in 1 example.

I think it's not too hard to print better error messages, so let's just go with that then.

**Comment by bobismijnnaam** [comment]
Okay, that's a valid concern. The best reason I can think of to keep this feature is that you want to have method calls in your contracts, i.e. \result.getSize() == 4. This pass helps with that, so I'd like to keep it.

**Comment by bobismijnnaam** [comment]
Some things that should be included when fixing this issue: 

- When you forget the return statement in a pure method, vercors crashes. A clear error message would be preferable. 
- When you use context with a permission, you get an error saying a function cannot have permissions in the post condition, but this should be reworded to pure method. Possibly this can be checked in the MethodsAsPureFunctions pass.
- When asserts are not thrown away, pure methods can be used as safe lemmas, which would be great! (Currently we have to trust the user to not change state within lemma methods) So asserts in pure methods would be supported in the near future ideally

**Comment by superaxander** [comment]
This gives the error `This method is marked as pure, but it cannot be converted to a function, since the method implementation cannot be restructured into a pure expression.` now, which I think is clear. This was fixed in #629
