### ISSUE TITLE
Unfolderror is not properly processed

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#733]
The following input:

```
class Tree {
  resource wf(Tree p) = true;
}

requires root.wf(null);
void markTree(Tree root) {
  boolean first = true;
  loop_invariant first ==> root.wf(null);
  while (first || root != null) {
    first = false;
    unfold root.wf(null);
  }
}
```

Gives the following output with vercors 2 alpha 2:

```
$ vct-alpha --verify BTT_error.pvl
[INFO] Starting verification
(2/3) Translation › (32/42) adt › (1/1) /home/bobe/Workbench/Tools/vercors_alpha/src/main/unive
(2/3) Translation › (32/42) adt › (1/1) /home/bobe/Workbench/Tools/vercors_alpha/src/main/unive
(2/3) Translation › (32/42) adt › (1/1) /home/bobe/Workbench/Tools/vercors_alpha/src/main/unive
[ERROR] Fatal error
scala.MatchError: There might be insufficient permission to access wf(root, null) (of class viper.silver.verifier.reasons$InsufficientPermission)
        at viper.api.SilverBackend.defer(SilverBackend.scala:213)
        at viper.api.SilverBackend.defer$(SilverBackend.scala:213)
        at viper.api.Silicon.defer(Silicon.scala:12)
        at viper.api.SilverBackend.processError(SilverBackend.scala:169)
        at viper.api.SilverBackend.processError$(SilverBackend.scala:84)
        at viper.api.Silicon.processError(Silicon.scala:12)
        at viper.api.SilverBackend.$anonfun$submit$7(SilverBackend.scala:77)
        at viper.api.SilverBackend.$anonfun$submit$7$adapted(SilverBackend.scala:77)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at viper.api.SilverBackend.$anonfun$submit$6(SilverBackend.scala:77)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at hre.progress.Progress$.withFrame(Progress.scala:120)
        at hre.progress.Progress$.dynamicMessages(Progress.scala:131)
        at viper.api.EntityTrackingReporter.withEntities(EntityTrackingReporter.scala:28)
        at viper.api.SilverBackend.submit(SilverBackend.scala:75)
        at viper.api.SilverBackend.submit$(SilverBackend.scala:36)
        at viper.api.Silicon.submit(Silicon.scala:12)
        at vct.main.Vercors.$anonfun$go$1(Vercors.scala:203)
        at hre.progress.Progress$.withFrame(Progress.scala:120)
        at hre.progress.Progress$.stages(Progress.scala:128)
        at vct.main.Vercors.go(Vercors.scala:143)
        at vct.main.RealMain$.selectMode(RealMain.scala:37)
        at vct.main.RealMain$.main(RealMain.scala:13)
        at vct.main.RealMain.main(RealMain.scala)

[████████████████████████████████████████████████████████████] 100.0%
```

Additionally, after printing the 100% bar, it hangs. I would expect this example to give an error that unfolding is not possible at the input level (so about `root.wf(null)`) instead of an error on the transformed predicate, and then terminate.

**Comment by niomaster** [comment]
Re: the termination issue, I'm not sure what's causing this. I think it has something to do with a worker thread hanging around that is not marked as daemon.
