### ISSUE TITLE
Cannot `\unfolding` a `read` predicate

### ISSUE THREAD

**Issue by bobismijnnaam** [utwente-fmt/vercors#763]
VerCors `ast` crashes on the following program:

```javascript
resource data() = true;

requires [read]data();
pure boolean f() = \unfolding [read]data() \in true;
```

Error:

```
Exception in thread "main" scala.MatchError: There might be insufficient permission to access data() (of class viper.silver.verifier.reasons$InsufficientPermission)
        at viper.api.SilverBackend.defer(SilverBackend.scala:227)
        at viper.api.SilverBackend.defer$(SilverBackend.scala:227)
        at viper.api.Silicon.defer(Silicon.scala:41)
        at viper.api.SilverBackend.processError(SilverBackend.scala:195)
        at viper.api.SilverBackend.processError$(SilverBackend.scala:98)
        at viper.api.Silicon.processError(Silicon.scala:41)
        at viper.api.SilverBackend.$anonfun$submit$9(SilverBackend.scala:92)
        at viper.api.SilverBackend.$anonfun$submit$9$adapted(SilverBackend.scala:92)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at viper.api.SilverBackend.$anonfun$submit$8(SilverBackend.scala:92)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at hre.progress.Progress$.withFrame(Progress.scala:121)
        at hre.progress.Progress$.dynamicMessages(Progress.scala:132)
        at viper.api.EntityTrackingReporter.withEntities(EntityTrackingReporter.scala:28)
        at viper.api.SilverBackend.submit(SilverBackend.scala:88)
        at viper.api.SilverBackend.submit$(SilverBackend.scala:44)
        at viper.api.Silicon.submit(Silicon.scala:41)
        at vct.main.stages.SilverBackend.$anonfun$run$1(Backend.scala:59)
        at vct.main.stages.SilverBackend.$anonfun$run$1$adapted(Backend.scala:58)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at vct.main.stages.SilverBackend.run(Backend.scala:58)
        at vct.main.stages.SilverBackend.run(Backend.scala:56)
        at vct.main.stages.UnitStages.runUnsafely(Stage.scala:74)
        at vct.main.stages.StagesPair.runUnsafely(Stage.scala:82)
        at vct.main.stages.StagesPair.runUnsafely(Stage.scala:80)
        at vct.main.stages.Stages.$anonfun$run$1(Stage.scala:59)
        at hre.progress.Progress$.withFrame(Progress.scala:121)
        at hre.progress.Progress$.stages(Progress.scala:129)
        at vct.main.stages.Stages.run(Stage.scala:59)
        at vct.main.stages.Stages.run$(Stage.scala:56)
        at vct.main.stages.StagesPair.run(Stage.scala:78)
        at vct.main.modes.Verify$.verifyWithOptions(Verify.scala:37)
        at vct.main.modes.Verify$.runOptions(Verify.scala:44)
        at vct.main.Main$.runOptions(Main.scala:61)
        at vct.main.Main$.main(Main.scala:29)
        at vct.main.Main.main(Main.scala)
```

I would expect this to verify. If this expectation is wrong, I guess we should at least have a case for this error. The stacktrace is also printed twice, is that intentional?

**Comment by ArmborstL** [comment]
Note: In Viper, this gets translated to
```
function f(): Bool
  requires acc(data(), scale(wildcard) * write)
{
  (unfolding acc(data(), scale(wildcard) * write) in true)
}
```
and the `scale` in the unfolding causes an error _"Function might not be well-formed. There might be insufficient permission to access data()"_. Removing the `scale` function in the `unfolding` statement fixes the issue for Viper (even if `scale` is still there in the `requires`). 
`scale` is defined as
```
function scale(amount: Perm): Perm
  requires amount >= 0 * write
{
  amount
}
```

**Comment by ArmborstL** [comment]
Second note: wrapping the program in a class causes the problem to appear in a different form: VerCors does not even reach the Viper stage, but already complains before:
```
A rewrite caused the AST to no longer typecheck:
======================================
At ..\temp\unfold_read.pvl:5:41:
--------------------------------------
    3
    4      requires [read]data();
                                              [------
    5      pure boolean f() = \unfolding [read]data() \in true;
                                               ------]
    6  }
    7
--------------------------------------
This expression is not a (scaled) predicate application
======================================
```
It is not clear why `data` would not be a predicate at this point.

**Comment by JLedelay** [comment]
In current VerCors, the pvl input given in the issue no longer crashes, but yields the following error:
```
======================================
At test.pvl:4:32:
--------------------------------------
    2
    3  requires [read]data();
                                     [----
    4  pure boolean f() = \unfolding [read]data() \in true;
                                      ----]
    5
--------------------------------------
You cannot have a wildcard outside of a permission statement.
======================================
```

Replacing `[read]` with `[1\2]` removed the error and gave successful verification.

However, putting this into a Java file gives a similar error to what @ArmborstL reported:
```java
public class C {
  /*@
  resource data() = true;

  requires [1\2]data();
  pure boolean test() = \unfolding [1\2]data() \in true; 
  @*/
}

```
```
The classToRef rewrite caused the AST to no longer typecheck:
======================================
At C.java:6:41:
--------------------------------------
    4
    5    requires [1\2]data();
                                              [------
    6    pure boolean test() = \unfolding [1\2]data() \in true;
                                               ------]
    7    @*/
    8  }
--------------------------------------
This expression is not a (scaled) predicate application
======================================
```

A workaround I found was to turn `data()` into an inline predicate, creating a new predicate `P()` which holds `[1\2]data()` and `\unfolding` that instead. For this small example, this is fine, but for a larger program with multiple different scaling factors (i.e. `write` and `[1\2]`), you need multiple such predicates, if you do want `data()` to be opaque.

```java
public class C {
  /*@
  inline resource data() = true;
  resource P() = [1\2]data();

  requires P();
  pure boolean test() = \unfolding P() \in true; 
  @*/
}
```

**Comment by bobismijnnaam** [comment]
@JLedelay I need to look a bit more thoroughly at this still but the following might be useful to you. You can give P a parameter that indicates the fraction, as follows:

```
public class C {
  /*@
  inline resource data() = true;
  resource P(frac x) = [x]data();

  requires P(1\2);
  pure boolean test() = \unfolding P(1\2) \in true; 
  @*/
}
```

**Comment by bobismijnnaam** [comment]
Related: https://github.com/utwente-fmt/vercors/discussions/891
