### ISSUE TITLE
VerCors crashes & hangs for static array in complex forall

### ISSUE THREAD

**Issue by ArmborstL** [utwente-fmt/vercors#789]
The program below leads VerCors to an exception (_"java.util.NoSuchElementException: None.get"_) at some point during the transformation process.
```java
public class InvertInjection {
  static int[] b;
  public void invert() {
    //@ assert (\forall int i; 0 <= i && i < 5; b[i] == -1 && b[0] != i);
  }
}
```
The problem goes away if the array `b` is not static, or if the `forall` does not have the `&&`.

<details><summary>Stack trace</summary>

```
Exception in thread "main" java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:627)
        at scala.None$.get(Option.scala:626)
        at vct.col.ast.SuccessorsProvider.$anonfun$succ$1(SuccessorsProvider.scala:23)
        at vct.col.ref.LazyRef.decl$lzycompute(LazyRef.scala:21)
        at vct.col.ref.LazyRef.decl(LazyRef.scala:20)
        at vct.col.ref.Ref.hashCode(Ref.scala:26)
        at vct.col.ref.Ref.hashCode$(Ref.scala:26)
        at vct.col.ref.LazyRef.hashCode(LazyRef.scala:8)
        at java.base/java.lang.Object.toString(Object.java:246)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1184)
        at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1179)
        at scala.collection.AbstractIterator.addString(Iterator.scala:1288)
        at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1129)
        at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1127)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1288)
        at scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:156)
        at vct.col.ast.node.NodeImpl.toString(NodeImpl.scala:61)
        at vct.col.ast.node.NodeImpl.toString$(NodeImpl.scala:51)
        at vct.col.ast.FunctionInvocation.toString(Node.scala:429)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1184)
        at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1179)
        at scala.collection.AbstractIterator.addString(Iterator.scala:1288)
        at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1129)
        at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1127)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1288)
        at scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:156)
        at vct.col.ast.node.NodeImpl.toString(NodeImpl.scala:61)
        at vct.col.ast.node.NodeImpl.toString$(NodeImpl.scala:51)
        at vct.col.ast.Deref.toString(Node.scala:403)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1184)
        at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1179)
        at scala.collection.AbstractIterator.addString(Iterator.scala:1288)
        at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1129)
        at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1127)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1288)
        at scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:156)
        at vct.col.ast.node.NodeImpl.toString(NodeImpl.scala:61)
        at vct.col.ast.node.NodeImpl.toString$(NodeImpl.scala:51)
        at vct.col.ast.ArraySubscript.toString(Node.scala:533)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1184)
        at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1179)
        at scala.collection.AbstractIterator.addString(Iterator.scala:1288)
        at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1129)
        at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1127)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1288)
        at scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:156)
        at vct.col.ast.node.NodeImpl.toString(NodeImpl.scala:61)
        at vct.col.ast.node.NodeImpl.toString$(NodeImpl.scala:51)
        at vct.col.ast.Neq.toString(Node.scala:507)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1187)
        at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1179)
        at scala.collection.AbstractIterator.addString(Iterator.scala:1288)
        at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1129)
        at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1127)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1288)
        at scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:156)
        at vct.col.ast.node.NodeImpl.toString(NodeImpl.scala:61)
        at vct.col.ast.node.NodeImpl.toString$(NodeImpl.scala:51)
        at vct.col.ast.Implies.toString(Node.scala:474)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at scala.collection.IterableOnceOps.addString(IterableOnce.scala:1187)
        at scala.collection.IterableOnceOps.addString$(IterableOnce.scala:1179)
        at scala.collection.AbstractIterator.addString(Iterator.scala:1288)
        at scala.collection.IterableOnceOps.mkString(IterableOnce.scala:1129)
        at scala.collection.IterableOnceOps.mkString$(IterableOnce.scala:1127)
        at scala.collection.AbstractIterator.mkString(Iterator.scala:1288)
        at scala.runtime.ScalaRunTime$._toString(ScalaRunTime.scala:156)
        at vct.col.ast.node.NodeImpl.toString(NodeImpl.scala:61)
        at vct.col.ast.node.NodeImpl.toString$(NodeImpl.scala:51)
        at vct.col.ast.Forall.toString(Node.scala:391)
        at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3031)
        at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2908)
        at java.base/java.util.Formatter.format(Formatter.java:2673)
        at java.base/java.util.Formatter.format(Formatter.java:2609)
        at java.base/java.lang.String.format(String.java:2897)
        at scala.collection.StringOps$.format$extension(StringOps.scala:989)
        at vct.col.rewrite.SimplifyNestedQuantifiers.dispatch(SimplifyNestedQuantifiers.scala:72)
        at vct.col.ast.RewriteHelpers$RewriteAnd.rewrite$default$2(RewriteHelpers.scala:1295)
        at vct.col.ast.AbstractRewriter$$anon$130.$anonfun$apply$296(AbstractRewriter.scala:17)
        at vct.col.ast.RewriteHelpers$RewriteAnd.rewrite(RewriteHelpers.scala:1296)
        at vct.col.ast.AbstractRewriter$$anon$130.apply(AbstractRewriter.scala:17)
        at vct.col.ast.AbstractRewriter$$anon$130.apply(AbstractRewriter.scala:17)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:154)
        at vct.col.rewrite.SimplifyNestedQuantifiers.dispatch(SimplifyNestedQuantifiers.scala:79)
        at vct.col.ast.RewriteHelpers$RewriteAssert.rewrite$default$1(RewriteHelpers.scala:297)
        at vct.col.ast.AbstractRewriter$$anon$279.$anonfun$apply$583(AbstractRewriter.scala:18)
        at vct.col.ast.RewriteHelpers$RewriteAssert.rewrite(RewriteHelpers.scala:298)
        at vct.col.ast.AbstractRewriter$$anon$279.apply(AbstractRewriter.scala:18)
        at vct.col.ast.AbstractRewriter$$anon$279.apply(AbstractRewriter.scala:18)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:142)
        at vct.col.rewrite.SimplifyNestedQuantifiers.dispatch(SimplifyNestedQuantifiers.scala:87)
        at vct.col.ast.RewriteHelpers$RewriteBlock.$anonfun$rewrite$default$1$17(RewriteHelpers.scala:412)
        at scala.collection.immutable.List.map(List.scala:246)
        at scala.collection.immutable.List.map(List.scala:79)
        at vct.col.ast.RewriteHelpers$RewriteBlock.rewrite$default$1(RewriteHelpers.scala:412)
        at vct.col.ast.AbstractRewriter$$anon$302.$anonfun$apply$619(AbstractRewriter.scala:18)
        at vct.col.ast.RewriteHelpers$RewriteBlock.rewrite(RewriteHelpers.scala:413)
        at vct.col.ast.AbstractRewriter$$anon$302.apply(AbstractRewriter.scala:18)
        at vct.col.ast.AbstractRewriter$$anon$302.apply(AbstractRewriter.scala:18)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:142)
        at vct.col.rewrite.SimplifyNestedQuantifiers.dispatch(SimplifyNestedQuantifiers.scala:87)
        at vct.col.ast.RewriteHelpers$RewriteScope.rewrite$default$2(RewriteHelpers.scala:417)
        at vct.col.ast.AbstractRewriter$$anon$303.$anonfun$apply$621(AbstractRewriter.scala:18)
        at vct.col.ast.RewriteHelpers$RewriteScope.$anonfun$rewrite$12(RewriteHelpers.scala:421)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:58)
        at vct.col.ast.RewriteHelpers$RewriteScope.$anonfun$rewrite$11(RewriteHelpers.scala:421)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:58)
        at vct.col.ast.RewriteHelpers$RewriteScope.$anonfun$rewrite$10(RewriteHelpers.scala:420)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:58)
        at vct.col.ast.RewriteHelpers$RewriteScope.rewrite(RewriteHelpers.scala:419)
        at vct.col.ast.AbstractRewriter$$anon$303.apply(AbstractRewriter.scala:18)
        at vct.col.ast.AbstractRewriter$$anon$303.apply(AbstractRewriter.scala:18)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:142)
        at vct.col.rewrite.SimplifyNestedQuantifiers.dispatch(SimplifyNestedQuantifiers.scala:87)
        at vct.col.ast.RewriteHelpers$RewriteInstanceMethod.$anonfun$rewrite$default$5$5(RewriteHelpers.scala:549)
        at scala.Option.map(Option.scala:242)
        at vct.col.ast.RewriteHelpers$RewriteInstanceMethod.rewrite$default$5(RewriteHelpers.scala:549)
        at vct.col.ast.AbstractRewriter$$anon$9.$anonfun$apply$38(AbstractRewriter.scala:13)
        at vct.col.ast.RewriteHelpers$RewriteInstanceMethod.$anonfun$rewrite$21(RewriteHelpers.scala:551)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:58)
        at vct.col.ast.RewriteHelpers$RewriteInstanceMethod.rewrite(RewriteHelpers.scala:551)
        at vct.col.ast.AbstractRewriter$$anon$9.apply(AbstractRewriter.scala:13)
        at vct.col.ast.AbstractRewriter$$anon$9.apply(AbstractRewriter.scala:13)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:47)
        at vct.col.rewrite.NonLatchingRewriter.dispatch(NonLatchingRewriter.scala:14)
        at vct.col.util.Scopes.$anonfun$dispatch$3(Scopes.scala:102)
        at vct.col.util.Scopes.$anonfun$dispatch$3$adapted(Scopes.scala:102)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at vct.col.util.Scopes.$anonfun$dispatch$2(Scopes.scala:102)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.collect(Scopes.scala:66)
        at vct.col.util.Scopes.dispatch(Scopes.scala:102)
        at vct.col.ast.RewriteHelpers$RewriteClass.rewrite$default$1(RewriteHelpers.scala:511)
        at vct.col.ast.AbstractRewriter$$anon$3.$anonfun$apply$4(AbstractRewriter.scala:13)
        at vct.col.ast.RewriteHelpers$RewriteClass.rewrite(RewriteHelpers.scala:512)
        at vct.col.ast.AbstractRewriter$$anon$3.apply(AbstractRewriter.scala:13)
        at vct.col.ast.AbstractRewriter$$anon$3.apply(AbstractRewriter.scala:13)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:47)
        at vct.col.rewrite.NonLatchingRewriter.dispatch(NonLatchingRewriter.scala:14)
        at vct.col.util.Scopes.$anonfun$dispatch$3(Scopes.scala:102)
        at vct.col.util.Scopes.$anonfun$dispatch$3$adapted(Scopes.scala:102)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at vct.col.util.Scopes.$anonfun$dispatch$2(Scopes.scala:102)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.collect(Scopes.scala:66)
        at vct.col.util.Scopes.dispatch(Scopes.scala:102)
        at vct.col.ast.RewriteHelpers$RewriteProgram.rewrite$default$1(RewriteHelpers.scala:19)
        at vct.col.ast.AbstractRewriter$$anon$450.$anonfun$apply$820(AbstractRewriter.scala:37)
        at vct.col.ast.RewriteHelpers$RewriteProgram.$anonfun$rewrite$5(RewriteHelpers.scala:25)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:58)
        at vct.col.ast.RewriteHelpers$RewriteProgram.$anonfun$rewrite$4(RewriteHelpers.scala:25)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:58)
        at vct.col.ast.RewriteHelpers$RewriteProgram.$anonfun$rewrite$3(RewriteHelpers.scala:24)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:58)
        at vct.col.ast.RewriteHelpers$RewriteProgram.$anonfun$rewrite$2(RewriteHelpers.scala:23)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:58)
        at vct.col.ast.RewriteHelpers$RewriteProgram.$anonfun$rewrite$1(RewriteHelpers.scala:22)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:58)
        at vct.col.ast.RewriteHelpers$RewriteProgram.rewrite(RewriteHelpers.scala:21)
        at vct.col.ast.AbstractRewriter$$anon$450.apply(AbstractRewriter.scala:37)
        at vct.col.ast.AbstractRewriter$$anon$450.apply(AbstractRewriter.scala:37)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:155)
        at vct.col.ast.RewriteHelpers$RewriteVerificationContext.rewrite$default$1(RewriteHelpers.scala:14)
        at vct.col.ast.AbstractRewriter$$anon$403.$anonfun$apply$748(AbstractRewriter.scala:28)
        at vct.col.ast.RewriteHelpers$RewriteVerificationContext.rewrite(RewriteHelpers.scala:15)
        at vct.col.ast.AbstractRewriter$$anon$403.apply(AbstractRewriter.scala:28)
        at vct.col.ast.AbstractRewriter$$anon$403.apply(AbstractRewriter.scala:28)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:148)
        at vct.col.rewrite.NonLatchingRewriter.dispatch(NonLatchingRewriter.scala:7)
        at vct.col.ast.RewriteHelpers$RewriteVerification.$anonfun$rewrite$default$1$1(RewriteHelpers.scala:9)
        at scala.collection.immutable.List.map(List.scala:246)
        at scala.collection.immutable.List.map(List.scala:79)
        at vct.col.ast.RewriteHelpers$RewriteVerification.rewrite$default$1(RewriteHelpers.scala:9)
        at vct.col.ast.AbstractRewriter$$anon$475.$anonfun$apply$829(AbstractRewriter.scala:41)
        at vct.col.ast.RewriteHelpers$RewriteVerification.rewrite(RewriteHelpers.scala:10)
        at vct.col.ast.AbstractRewriter$$anon$475.apply(AbstractRewriter.scala:41)
        at vct.col.ast.AbstractRewriter$$anon$475.apply(AbstractRewriter.scala:41)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:146)
        at vct.col.rewrite.NonLatchingRewriter.dispatch(NonLatchingRewriter.scala:6)
        at vct.main.stages.Transformation.$anonfun$run$3(Transformation.scala:93)
        at vct.main.stages.Transformation.$anonfun$run$3$adapted(Transformation.scala:88)
        at hre.progress.Progress$.$anonfun$foreach$2(Progress.scala:151)
        at hre.progress.Progress$.$anonfun$foreach$2$adapted(Progress.scala:150)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at hre.progress.Progress$.$anonfun$foreach$1(Progress.scala:150)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at hre.progress.Progress$.withFrame(Progress.scala:132)
        at hre.progress.Progress$.seqStages(Progress.scala:146)
        at hre.progress.Progress$.foreach(Progress.scala:150)
        at vct.main.stages.Transformation.run(Transformation.scala:88)
        at vct.main.stages.Transformation.run(Transformation.scala:64)
        at vct.main.stages.UnitStages.runUnsafely(Stage.scala:74)
        at vct.main.stages.StagesPair.runUnsafely(Stage.scala:82)
        at vct.main.stages.StagesPair.runUnsafely(Stage.scala:80)
        at vct.main.stages.StagesPair.runUnsafely(Stage.scala:80)
        at vct.main.stages.Stages.$anonfun$run$1(Stage.scala:59)
        at hre.progress.Progress$.withFrame(Progress.scala:132)
        at hre.progress.Progress$.stages(Progress.scala:140)
        at vct.main.stages.Stages.run(Stage.scala:59)
        at vct.main.stages.Stages.run$(Stage.scala:56)
        at vct.main.stages.StagesPair.run(Stage.scala:78)
        at vct.main.modes.Verify$.verifyWithOptions(Verify.scala:40)
        at vct.main.modes.Verify$.runOptions(Verify.scala:60)
        at vct.main.Main$.runOptions(Main.scala:60)
        at vct.main.Main$.main(Main.scala:29)
        at vct.main.Main.main(Main.scala)
```
</details> 

Also, in a maybe unrelated error, the (Windows) script hangs after the exception, rather than terminating.

**Comment by ArmborstL** [comment]
Note: the hanging under Windows also occurs if I circumvent the runscripts and invoke `java -Xss128M -cp"[...]" vct.main.Main [...]` directly. So I'm not sure if the problem is caused by VerCors or if it's in the JVM... 
It occurs with both openJDK 11 and 18.

**Comment by niomaster** [comment]
Yeah, I've noticed this in linux as well, it seems to happen mostly when VerCors crashes for some reason. I suspect that there is a non-daemon thread still hanging around, but I've not been able to identify it.
