### ISSUE TITLE
\type fails on array

### ISSUE THREAD

**Issue by ArmborstL** [utwente-fmt/vercors#914]
VerCors syntactically supports `\type` specification, such as `\typeof(\result) == \type(Object)`. However, if the given type is an array, VerCors crashes:
```java
class T {
  //@ ensures \typeof(\result) == \type(int[]);
  int[] nu() {
    return new int[2];
  }
}
```
gives _"scala.NotImplementedError: an implementation is missing"_ for `ClassToRef.scala`.
<details>
<summary> Stack Trace</summary>

```
[ERROR] Unrecoverable error: an implementation is missing
scala.NotImplementedError: an implementation is missing
        at scala.Predef$.$qmark$qmark$qmark(Predef.scala:345)
        at vct.col.rewrite.ClassToRef.dispatch(ClassToRef.scala:255)
        at vct.col.ast.RewriteEqImpl.rewrite$default$2(RewriteEqImpl.scala:8)
        at vct.col.ast.RewriteEqImpl.rewrite$default$2$(RewriteEqImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteEq.rewrite$default$2(RewriteHelpers.scala:297)
        at vct.col.ast.RewriteEqImpl.$anonfun$rewriteDefault$2(RewriteEqImpl.scala:7)
        at vct.col.ast.RewriteEqImpl.rewrite(RewriteEqImpl.scala:9)
        at vct.col.ast.RewriteEqImpl.rewrite$(RewriteEqImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteEq.rewrite(RewriteHelpers.scala:297)
        at vct.col.ast.RewriteEqImpl.rewriteDefault(RewriteEqImpl.scala:7)
        at vct.col.ast.RewriteEqImpl.rewriteDefault$(RewriteEqImpl.scala:7)
        at vct.col.ast.RewriteHelpers$RewriteEq.rewriteDefault(RewriteHelpers.scala:297)
        at vct.col.ast.AbstractRewriter$$anon$316.apply(AbstractRewriter.scala:28)
        at vct.col.ast.AbstractRewriter$$anon$316.apply(AbstractRewriter.scala:28)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:151)
        at vct.col.rewrite.ClassToRef.dispatch(ClassToRef.scala:272)
        at vct.col.ast.RewriteUnitAccountedPredicateImpl.rewrite$default$1(RewriteUnitAccountedPredicateImpl.scala:8)
        at vct.col.ast.RewriteUnitAccountedPredicateImpl.rewrite$default$1$(RewriteUnitAccountedPredicateImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteUnitAccountedPredicate.rewrite$default$1(RewriteHelpers.scala:130)
        at vct.col.ast.RewriteUnitAccountedPredicateImpl.$anonfun$rewriteDefault$1(RewriteUnitAccountedPredicateImpl.scala:7)
        at vct.col.ast.RewriteUnitAccountedPredicateImpl.rewrite(RewriteUnitAccountedPredicateImpl.scala:9)
        at vct.col.ast.RewriteUnitAccountedPredicateImpl.rewrite$(RewriteUnitAccountedPredicateImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteUnitAccountedPredicate.rewrite(RewriteHelpers.scala:130)
        at vct.col.ast.RewriteUnitAccountedPredicateImpl.rewriteDefault(RewriteUnitAccountedPredicateImpl.scala:7)
        at vct.col.ast.RewriteUnitAccountedPredicateImpl.rewriteDefault$(RewriteUnitAccountedPredicateImpl.scala:7)
        at vct.col.ast.RewriteHelpers$RewriteUnitAccountedPredicate.rewriteDefault(RewriteHelpers.scala:130)
        at vct.col.ast.AbstractRewriter$$anon$157.apply(AbstractRewriter.scala:25)
        at vct.col.ast.AbstractRewriter$$anon$157.apply(AbstractRewriter.scala:25)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:148)
        at vct.col.rewrite.NonLatchingRewriter.dispatch(NonLatchingRewriter.scala:18)
        at vct.col.ast.RewriteSplitAccountedPredicateImpl.rewrite$default$2(RewriteSplitAccountedPredicateImpl.scala:8)
        at vct.col.ast.RewriteSplitAccountedPredicateImpl.rewrite$default$2$(RewriteSplitAccountedPredicateImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteSplitAccountedPredicate.rewrite$default$2(RewriteHelpers.scala:131)
        at vct.col.ast.RewriteSplitAccountedPredicateImpl.$anonfun$rewriteDefault$2(RewriteSplitAccountedPredicateImpl.scala:7)
        at vct.col.ast.RewriteSplitAccountedPredicateImpl.rewrite(RewriteSplitAccountedPredicateImpl.scala:9)
        at vct.col.ast.RewriteSplitAccountedPredicateImpl.rewrite$(RewriteSplitAccountedPredicateImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteSplitAccountedPredicate.rewrite(RewriteHelpers.scala:131)
        at vct.col.ast.RewriteSplitAccountedPredicateImpl.rewriteDefault(RewriteSplitAccountedPredicateImpl.scala:7)
        at vct.col.ast.RewriteSplitAccountedPredicateImpl.rewriteDefault$(RewriteSplitAccountedPredicateImpl.scala:7)
        at vct.col.ast.RewriteHelpers$RewriteSplitAccountedPredicate.rewriteDefault(RewriteHelpers.scala:131)
        at vct.col.ast.AbstractRewriter$$anon$158.apply(AbstractRewriter.scala:25)
        at vct.col.ast.AbstractRewriter$$anon$158.apply(AbstractRewriter.scala:25)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:148)
        at vct.col.rewrite.NonLatchingRewriter.dispatch(NonLatchingRewriter.scala:18)
        at vct.col.ast.RewriteApplicableContractImpl.rewrite$default$2(RewriteApplicableContractImpl.scala:8)
        at vct.col.ast.RewriteApplicableContractImpl.rewrite$default$2$(RewriteApplicableContractImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteApplicableContract.rewrite$default$2(RewriteHelpers.scala:129)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$23(ClassToRef.scala:159)
        at vct.col.ast.RewriteApplicableContractImpl.rewrite(RewriteApplicableContractImpl.scala:9)
        at vct.col.ast.RewriteApplicableContractImpl.rewrite$(RewriteApplicableContractImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteApplicableContract.rewrite(RewriteHelpers.scala:129)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$18(ClassToRef.scala:159)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:43)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$17(ClassToRef.scala:150)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$4(ClassToRef.scala:150)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at vct.col.rewrite.ClassToRef.dispatch(ClassToRef.scala:116)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$3(ClassToRef.scala:104)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$3$adapted(ClassToRef.scala:104)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$2(ClassToRef.scala:104)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.collect(Scopes.scala:51)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$1(ClassToRef.scala:103)
        at vct.col.ast.RewriteProgramImpl.$anonfun$rewrite$6(RewriteProgramImpl.scala:15)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:43)
        at vct.col.ast.RewriteProgramImpl.$anonfun$rewrite$5(RewriteProgramImpl.scala:15)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:43)
        at vct.col.ast.RewriteProgramImpl.$anonfun$rewrite$4(RewriteProgramImpl.scala:14)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:43)
        at vct.col.ast.RewriteProgramImpl.$anonfun$rewrite$3(RewriteProgramImpl.scala:13)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:43)
        at vct.col.ast.RewriteProgramImpl.$anonfun$rewrite$2(RewriteProgramImpl.scala:12)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:43)
        at vct.col.ast.RewriteProgramImpl.$anonfun$rewrite$1(RewriteProgramImpl.scala:11)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:43)
        at vct.col.ast.RewriteProgramImpl.rewrite(RewriteProgramImpl.scala:10)
        at vct.col.ast.RewriteProgramImpl.rewrite$(RewriteProgramImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteProgram.rewrite(RewriteHelpers.scala:9)
        at vct.col.rewrite.ClassToRef.dispatch(ClassToRef.scala:103)
        at vct.col.ast.RewriteVerificationContextImpl.rewrite$default$1(RewriteVerificationContextImpl.scala:8)
        at vct.col.ast.RewriteVerificationContextImpl.rewrite$default$1$(RewriteVerificationContextImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteVerificationContext.rewrite$default$1(RewriteHelpers.scala:8)
        at vct.col.ast.RewriteVerificationContextImpl.$anonfun$rewriteDefault$1(RewriteVerificationContextImpl.scala:7)
        at vct.col.ast.RewriteVerificationContextImpl.rewrite(RewriteVerificationContextImpl.scala:9)
        at vct.col.ast.RewriteVerificationContextImpl.rewrite$(RewriteVerificationContextImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteVerificationContext.rewrite(RewriteHelpers.scala:8)
        at vct.col.ast.RewriteVerificationContextImpl.rewriteDefault(RewriteVerificationContextImpl.scala:7)
        at vct.col.ast.RewriteVerificationContextImpl.rewriteDefault$(RewriteVerificationContextImpl.scala:7)
        at vct.col.ast.RewriteHelpers$RewriteVerificationContext.rewriteDefault(RewriteHelpers.scala:8)
        at vct.col.ast.AbstractRewriter$$anon$43.apply(AbstractRewriter.scala:14)
        at vct.col.ast.AbstractRewriter$$anon$43.apply(AbstractRewriter.scala:14)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:137)
        at vct.col.rewrite.NonLatchingRewriter.dispatch(NonLatchingRewriter.scala:7)
        at vct.col.ast.RewriteVerificationImpl.$anonfun$rewrite$default$1$1(RewriteVerificationImpl.scala:8)
        at scala.collection.immutable.List.map(List.scala:246)
        at scala.collection.immutable.List.map(List.scala:79)
        at vct.col.ast.RewriteVerificationImpl.rewrite$default$1(RewriteVerificationImpl.scala:8)
        at vct.col.ast.RewriteVerificationImpl.rewrite$default$1$(RewriteVerificationImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteVerification.rewrite$default$1(RewriteHelpers.scala:7)
        at vct.col.ast.RewriteVerificationImpl.$anonfun$rewriteDefault$1(RewriteVerificationImpl.scala:7)
        at vct.col.ast.RewriteVerificationImpl.rewrite(RewriteVerificationImpl.scala:9)
        at vct.col.ast.RewriteVerificationImpl.rewrite$(RewriteVerificationImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteVerification.rewrite(RewriteHelpers.scala:7)
        at vct.col.ast.RewriteVerificationImpl.rewriteDefault(RewriteVerificationImpl.scala:7)
        at vct.col.ast.RewriteVerificationImpl.rewriteDefault$(RewriteVerificationImpl.scala:7)
        at vct.col.ast.RewriteHelpers$RewriteVerification.rewriteDefault(RewriteHelpers.scala:7)
        at vct.col.ast.AbstractRewriter$$anon$42.apply(AbstractRewriter.scala:13)
        at vct.col.ast.AbstractRewriter$$anon$42.apply(AbstractRewriter.scala:13)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:136)
        at vct.col.rewrite.NonLatchingRewriter.dispatch(NonLatchingRewriter.scala:6)
        at vct.main.stages.Transformation.$anonfun$run$3(Transformation.scala:106)
        at vct.main.stages.Transformation.$anonfun$run$3$adapted(Transformation.scala:101)
        at hre.progress.Progress$.$anonfun$foreach$2(Progress.scala:151)
        at hre.progress.Progress$.$anonfun$foreach$2$adapted(Progress.scala:150)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at hre.progress.Progress$.$anonfun$foreach$1(Progress.scala:150)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at hre.progress.Progress$.withFrame(Progress.scala:132)
        at hre.progress.Progress$.seqStages(Progress.scala:146)
        at hre.progress.Progress$.foreach(Progress.scala:150)
        at vct.main.stages.Transformation.run(Transformation.scala:101)
        at vct.main.stages.Transformation.run(Transformation.scala:77)
        at hre.stages.UnitStages.runUnsafely(Stages.scala:42)
        at hre.stages.StagesPair.runUnsafely(Stages.scala:50)
        at hre.stages.StagesPair.runUnsafely(Stages.scala:48)
        at hre.stages.StagesPair.runUnsafely(Stages.scala:48)
        at hre.stages.Stages.$anonfun$run$1(Stages.scala:27)
        at hre.progress.Progress$.withFrame(Progress.scala:132)
        at hre.progress.Progress$.stages(Progress.scala:140)
        at hre.stages.Stages.run(Stages.scala:27)
        at hre.stages.Stages.run$(Stages.scala:24)
        at hre.stages.StagesPair.run(Stages.scala:46)
        at vct.main.modes.Verify$.verifyWithOptions(Verify.scala:40)
        at vct.main.modes.Verify$.runOptions(Verify.scala:68)
        at vct.main.Main$.runOptions(Main.scala:80)
        at vct.main.Main$.main(Main.scala:38)
        at vct.main.Main.main(Main.scala)
Exception in thread "main" scala.NotImplementedError: an implementation is missing
        at scala.Predef$.$qmark$qmark$qmark(Predef.scala:345)
        at vct.col.rewrite.ClassToRef.dispatch(ClassToRef.scala:255)
        at vct.col.ast.RewriteEqImpl.rewrite$default$2(RewriteEqImpl.scala:8)
        at vct.col.ast.RewriteEqImpl.rewrite$default$2$(RewriteEqImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteEq.rewrite$default$2(RewriteHelpers.scala:297)
        at vct.col.ast.RewriteEqImpl.$anonfun$rewriteDefault$2(RewriteEqImpl.scala:7)
        at vct.col.ast.RewriteEqImpl.rewrite(RewriteEqImpl.scala:9)
        at vct.col.ast.RewriteEqImpl.rewrite$(RewriteEqImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteEq.rewrite(RewriteHelpers.scala:297)
        at vct.col.ast.RewriteEqImpl.rewriteDefault(RewriteEqImpl.scala:7)
        at vct.col.ast.RewriteEqImpl.rewriteDefault$(RewriteEqImpl.scala:7)
        at vct.col.ast.RewriteHelpers$RewriteEq.rewriteDefault(RewriteHelpers.scala:297)
        at vct.col.ast.AbstractRewriter$$anon$316.apply(AbstractRewriter.scala:28)
        at vct.col.ast.AbstractRewriter$$anon$316.apply(AbstractRewriter.scala:28)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:151)
        at vct.col.rewrite.ClassToRef.dispatch(ClassToRef.scala:272)
        at vct.col.ast.RewriteUnitAccountedPredicateImpl.rewrite$default$1(RewriteUnitAccountedPredicateImpl.scala:8)
        at vct.col.ast.RewriteUnitAccountedPredicateImpl.rewrite$default$1$(RewriteUnitAccountedPredicateImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteUnitAccountedPredicate.rewrite$default$1(RewriteHelpers.scala:130)
        at vct.col.ast.RewriteUnitAccountedPredicateImpl.$anonfun$rewriteDefault$1(RewriteUnitAccountedPredicateImpl.scala:7)
        at vct.col.ast.RewriteUnitAccountedPredicateImpl.rewrite(RewriteUnitAccountedPredicateImpl.scala:9)
        at vct.col.ast.RewriteUnitAccountedPredicateImpl.rewrite$(RewriteUnitAccountedPredicateImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteUnitAccountedPredicate.rewrite(RewriteHelpers.scala:130)
        at vct.col.ast.RewriteUnitAccountedPredicateImpl.rewriteDefault(RewriteUnitAccountedPredicateImpl.scala:7)
        at vct.col.ast.RewriteUnitAccountedPredicateImpl.rewriteDefault$(RewriteUnitAccountedPredicateImpl.scala:7)
        at vct.col.ast.RewriteHelpers$RewriteUnitAccountedPredicate.rewriteDefault(RewriteHelpers.scala:130)
        at vct.col.ast.AbstractRewriter$$anon$157.apply(AbstractRewriter.scala:25)
        at vct.col.ast.AbstractRewriter$$anon$157.apply(AbstractRewriter.scala:25)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:148)
        at vct.col.rewrite.NonLatchingRewriter.dispatch(NonLatchingRewriter.scala:18)
        at vct.col.ast.RewriteSplitAccountedPredicateImpl.rewrite$default$2(RewriteSplitAccountedPredicateImpl.scala:8)
        at vct.col.ast.RewriteSplitAccountedPredicateImpl.rewrite$default$2$(RewriteSplitAccountedPredicateImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteSplitAccountedPredicate.rewrite$default$2(RewriteHelpers.scala:131)
        at vct.col.ast.RewriteSplitAccountedPredicateImpl.$anonfun$rewriteDefault$2(RewriteSplitAccountedPredicateImpl.scala:7)
        at vct.col.ast.RewriteSplitAccountedPredicateImpl.rewrite(RewriteSplitAccountedPredicateImpl.scala:9)
        at vct.col.ast.RewriteSplitAccountedPredicateImpl.rewrite$(RewriteSplitAccountedPredicateImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteSplitAccountedPredicate.rewrite(RewriteHelpers.scala:131)
        at vct.col.ast.RewriteSplitAccountedPredicateImpl.rewriteDefault(RewriteSplitAccountedPredicateImpl.scala:7)
        at vct.col.ast.RewriteSplitAccountedPredicateImpl.rewriteDefault$(RewriteSplitAccountedPredicateImpl.scala:7)
        at vct.col.ast.RewriteHelpers$RewriteSplitAccountedPredicate.rewriteDefault(RewriteHelpers.scala:131)
        at vct.col.ast.AbstractRewriter$$anon$158.apply(AbstractRewriter.scala:25)
        at vct.col.ast.AbstractRewriter$$anon$158.apply(AbstractRewriter.scala:25)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:148)
        at vct.col.rewrite.NonLatchingRewriter.dispatch(NonLatchingRewriter.scala:18)
        at vct.col.ast.RewriteApplicableContractImpl.rewrite$default$2(RewriteApplicableContractImpl.scala:8)
        at vct.col.ast.RewriteApplicableContractImpl.rewrite$default$2$(RewriteApplicableContractImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteApplicableContract.rewrite$default$2(RewriteHelpers.scala:129)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$23(ClassToRef.scala:159)
        at vct.col.ast.RewriteApplicableContractImpl.rewrite(RewriteApplicableContractImpl.scala:9)
        at vct.col.ast.RewriteApplicableContractImpl.rewrite$(RewriteApplicableContractImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteApplicableContract.rewrite(RewriteHelpers.scala:129)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$18(ClassToRef.scala:159)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:43)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$17(ClassToRef.scala:150)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$4(ClassToRef.scala:150)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at vct.col.rewrite.ClassToRef.dispatch(ClassToRef.scala:116)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$3(ClassToRef.scala:104)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$3$adapted(ClassToRef.scala:104)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$2(ClassToRef.scala:104)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.collect(Scopes.scala:51)
        at vct.col.rewrite.ClassToRef.$anonfun$dispatch$1(ClassToRef.scala:103)
        at vct.col.ast.RewriteProgramImpl.$anonfun$rewrite$6(RewriteProgramImpl.scala:15)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:43)
        at vct.col.ast.RewriteProgramImpl.$anonfun$rewrite$5(RewriteProgramImpl.scala:15)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:43)
        at vct.col.ast.RewriteProgramImpl.$anonfun$rewrite$4(RewriteProgramImpl.scala:14)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:43)
        at vct.col.ast.RewriteProgramImpl.$anonfun$rewrite$3(RewriteProgramImpl.scala:13)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:43)
        at vct.col.ast.RewriteProgramImpl.$anonfun$rewrite$2(RewriteProgramImpl.scala:12)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:43)
        at vct.col.ast.RewriteProgramImpl.$anonfun$rewrite$1(RewriteProgramImpl.scala:11)
        at hre.util.ScopedStack.having(ScopedStack.scala:34)
        at vct.col.util.Scopes.scope(Scopes.scala:43)
        at vct.col.ast.RewriteProgramImpl.rewrite(RewriteProgramImpl.scala:10)
        at vct.col.ast.RewriteProgramImpl.rewrite$(RewriteProgramImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteProgram.rewrite(RewriteHelpers.scala:9)
        at vct.col.rewrite.ClassToRef.dispatch(ClassToRef.scala:103)
        at vct.col.ast.RewriteVerificationContextImpl.rewrite$default$1(RewriteVerificationContextImpl.scala:8)
        at vct.col.ast.RewriteVerificationContextImpl.rewrite$default$1$(RewriteVerificationContextImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteVerificationContext.rewrite$default$1(RewriteHelpers.scala:8)
        at vct.col.ast.RewriteVerificationContextImpl.$anonfun$rewriteDefault$1(RewriteVerificationContextImpl.scala:7)
        at vct.col.ast.RewriteVerificationContextImpl.rewrite(RewriteVerificationContextImpl.scala:9)
        at vct.col.ast.RewriteVerificationContextImpl.rewrite$(RewriteVerificationContextImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteVerificationContext.rewrite(RewriteHelpers.scala:8)
        at vct.col.ast.RewriteVerificationContextImpl.rewriteDefault(RewriteVerificationContextImpl.scala:7)
        at vct.col.ast.RewriteVerificationContextImpl.rewriteDefault$(RewriteVerificationContextImpl.scala:7)
        at vct.col.ast.RewriteHelpers$RewriteVerificationContext.rewriteDefault(RewriteHelpers.scala:8)
        at vct.col.ast.AbstractRewriter$$anon$43.apply(AbstractRewriter.scala:14)
        at vct.col.ast.AbstractRewriter$$anon$43.apply(AbstractRewriter.scala:14)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:137)
        at vct.col.rewrite.NonLatchingRewriter.dispatch(NonLatchingRewriter.scala:7)
        at vct.col.ast.RewriteVerificationImpl.$anonfun$rewrite$default$1$1(RewriteVerificationImpl.scala:8)
        at scala.collection.immutable.List.map(List.scala:246)
        at scala.collection.immutable.List.map(List.scala:79)
        at vct.col.ast.RewriteVerificationImpl.rewrite$default$1(RewriteVerificationImpl.scala:8)
        at vct.col.ast.RewriteVerificationImpl.rewrite$default$1$(RewriteVerificationImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteVerification.rewrite$default$1(RewriteHelpers.scala:7)
        at vct.col.ast.RewriteVerificationImpl.$anonfun$rewriteDefault$1(RewriteVerificationImpl.scala:7)
        at vct.col.ast.RewriteVerificationImpl.rewrite(RewriteVerificationImpl.scala:9)
        at vct.col.ast.RewriteVerificationImpl.rewrite$(RewriteVerificationImpl.scala:8)
        at vct.col.ast.RewriteHelpers$RewriteVerification.rewrite(RewriteHelpers.scala:7)
        at vct.col.ast.RewriteVerificationImpl.rewriteDefault(RewriteVerificationImpl.scala:7)
        at vct.col.ast.RewriteVerificationImpl.rewriteDefault$(RewriteVerificationImpl.scala:7)
        at vct.col.ast.RewriteHelpers$RewriteVerification.rewriteDefault(RewriteHelpers.scala:7)
        at vct.col.ast.AbstractRewriter$$anon$42.apply(AbstractRewriter.scala:13)
        at vct.col.ast.AbstractRewriter$$anon$42.apply(AbstractRewriter.scala:13)
        at vct.col.ast.AbstractRewriter.rewriteDefault(AbstractRewriter.scala:136)
        at vct.col.rewrite.NonLatchingRewriter.dispatch(NonLatchingRewriter.scala:6)
        at vct.main.stages.Transformation.$anonfun$run$3(Transformation.scala:106)
        at vct.main.stages.Transformation.$anonfun$run$3$adapted(Transformation.scala:101)
        at hre.progress.Progress$.$anonfun$foreach$2(Progress.scala:151)
        at hre.progress.Progress$.$anonfun$foreach$2$adapted(Progress.scala:150)
        at scala.collection.immutable.List.foreach(List.scala:333)
        at hre.progress.Progress$.$anonfun$foreach$1(Progress.scala:150)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
        at hre.progress.Progress$.withFrame(Progress.scala:132)
        at hre.progress.Progress$.seqStages(Progress.scala:146)
        at hre.progress.Progress$.foreach(Progress.scala:150)
        at vct.main.stages.Transformation.run(Transformation.scala:101)
        at vct.main.stages.Transformation.run(Transformation.scala:77)
        at hre.stages.UnitStages.runUnsafely(Stages.scala:42)
        at hre.stages.StagesPair.runUnsafely(Stages.scala:50)
        at hre.stages.StagesPair.runUnsafely(Stages.scala:48)
        at hre.stages.StagesPair.runUnsafely(Stages.scala:48)
        at hre.stages.Stages.$anonfun$run$1(Stages.scala:27)
        at hre.progress.Progress$.withFrame(Progress.scala:132)
        at hre.progress.Progress$.stages(Progress.scala:140)
        at hre.stages.Stages.run(Stages.scala:27)
        at hre.stages.Stages.run$(Stages.scala:24)
        at hre.stages.StagesPair.run(Stages.scala:46)
        at vct.main.modes.Verify$.verifyWithOptions(Verify.scala:40)
        at vct.main.modes.Verify$.runOptions(Verify.scala:68)
        at vct.main.Main$.runOptions(Main.scala:80)
        at vct.main.Main$.main(Main.scala:38)
        at vct.main.Main.main(Main.scala)
```
</details>

I'm not sure how well `\typeof` and `\type` are still supported (see https://github.com/utwente-fmt/vercors/issues/454), so feel free to close this issue if it is a "won't fix".

**Comment by ArmborstL** [comment]
Maybe related: having a field `Object[] arr` and using `\typeof(arr)` gives _"Expected the type of this expression to be \`Ref\`, but got Ref[]."_, pointing to the `arr` inside the `\typeof`.

**Comment by niomaster** [comment]
The intention is to support this way better, and have `\type`, `\typeof` follow the VerCors type hierarchy (so e.g. `a instanceof B` will be `a != null && \typeof(a) <= \type(B)`)
