### ISSUE TITLE
Crash when using non-imported files

### ISSUE THREAD

**Issue by JLedelay** [utwente-fmt/vercors#934]
Using the following input file and command:
```vercors\bin\vct Test.java```

```java
package com.test;

class Test extends NotImported {
	
}
```
causes a crash in VerCors with the following output:
```
[ERROR] Unrecoverable error: Cannot invoke "java.io.File.getName()" because "file" is null
java.lang.NullPointerException: Cannot invoke "java.io.File.getName()" because "file" is null
        at vct.col.resolve.lang.Java$.$anonfun$findLibraryJavaType$8(Java.scala:189)
        at scala.collection.immutable.List.foldRight(List.scala:352)
        at vct.col.resolve.lang.Java$.$anonfun$findLibraryJavaType$6(Java.scala:188)
        at scala.Option.flatMap(Option.scala:283)
        at vct.col.resolve.lang.Java$.$anonfun$findLibraryJavaType$5(Java.scala:187)
        at scala.Option$WithFilter.flatMap(Option.scala:283)
        at vct.col.resolve.lang.Java$.$anonfun$findLibraryJavaType$3(Java.scala:186)
        at scala.Option.flatMap(Option.scala:283)
        at vct.col.resolve.lang.Java$.$anonfun$findLibraryJavaType$2(Java.scala:185)
        at hre.util.FuncTools$.$anonfun$firstOption$4(FuncTools.scala:11)
        at scala.Option.orElse(Option.scala:477)
        at hre.util.FuncTools$.$anonfun$firstOption$3(FuncTools.scala:11)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at hre.util.FuncTools$.firstOption(FuncTools.scala:11)
        at vct.col.resolve.lang.Java$.$anonfun$findLibraryJavaType$1(Java.scala:178)
        at scala.Option.flatMap(Option.scala:283)
        at vct.col.resolve.lang.Java$.findLibraryJavaType(Java.scala:177)
        at vct.col.resolve.lang.Java$.$anonfun$findJavaTypeName$3(Java.scala:232)
        at hre.util.FuncTools$.$anonfun$firstOption$4(FuncTools.scala:11)
        at scala.Option.orElse(Option.scala:477)
        at hre.util.FuncTools$.$anonfun$firstOption$3(FuncTools.scala:11)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at hre.util.FuncTools$.firstOption(FuncTools.scala:11)
        at vct.col.resolve.lang.Java$.$anonfun$findJavaTypeName$2(Java.scala:232)
...
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.io.File.getName()" because "file" is null
        at vct.col.resolve.lang.Java$.$anonfun$findLibraryJavaType$8(Java.scala:189)
        at scala.collection.immutable.List.foldRight(List.scala:352)
        at vct.col.resolve.lang.Java$.$anonfun$findLibraryJavaType$6(Java.scala:188)
        at scala.Option.flatMap(Option.scala:283)
        at vct.col.resolve.lang.Java$.$anonfun$findLibraryJavaType$5(Java.scala:187)
        at scala.Option$WithFilter.flatMap(Option.scala:283)
        at vct.col.resolve.lang.Java$.$anonfun$findLibraryJavaType$3(Java.scala:186)
        at scala.Option.flatMap(Option.scala:283)
        at vct.col.resolve.lang.Java$.$anonfun$findLibraryJavaType$2(Java.scala:185)
        at hre.util.FuncTools$.$anonfun$firstOption$4(FuncTools.scala:11)
        at scala.Option.orElse(Option.scala:477)
        at hre.util.FuncTools$.$anonfun$firstOption$3(FuncTools.scala:11)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at hre.util.FuncTools$.firstOption(FuncTools.scala:11)
        at vct.col.resolve.lang.Java$.$anonfun$findLibraryJavaType$1(Java.scala:178)
        at scala.Option.flatMap(Option.scala:283)
        at vct.col.resolve.lang.Java$.findLibraryJavaType(Java.scala:177)
        at vct.col.resolve.lang.Java$.$anonfun$findJavaTypeName$3(Java.scala:232)
        at hre.util.FuncTools$.$anonfun$firstOption$4(FuncTools.scala:11)
        at scala.Option.orElse(Option.scala:477)
        at hre.util.FuncTools$.$anonfun$firstOption$3(FuncTools.scala:11)
        at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
        at scala.collection.LinearSeqOps.foldLeft$(LinearSeq.scala:165)
        at scala.collection.immutable.List.foldLeft(List.scala:79)
        at hre.util.FuncTools$.firstOption(FuncTools.scala:11)
        at vct.col.resolve.lang.Java$.$anonfun$findJavaTypeName$2(Java.scala:232)
        at scala.Option.orElse(Option.scala:477)
        at vct.col.resolve.lang.Java$.findJavaTypeName(Java.scala:232)
...
```

Removing the `package com.test;` line changes the error message to: `[ERROR] Unrecoverable error: Cannot invoke "java.io.File.getName()" because "baseFile" is null`

I'd expect this to exit gracefully with an error message referring to the usage of the class that was not found.

**Comment by JLedelay** [comment]
Yes, that fixes it. Thanks!
