### ISSUE TITLE
Progress printing uses Linux-internal functionality

### ISSUE THREAD

**Issue by ArmborstL** [utwente-fmt/vercors#995]
Trying to run the [VerifyThis pre-release of VerCors](https://github.com/utwente-fmt/vercors/releases/tag/untagged-fa98068afc4b1c2fd06f) on Windows causes the following error:
```
Unrecoverable error: Error looking up function 'getrusage': The specified procedure could not be found.
java.lang.UnsatisfiedLinkError: Error looking up function 'getrusage': The specified procedure could not be found.

        at com.sun.jna.Function.<init>(Function.java:252)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:620)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:596)
        at com.sun.jna.NativeLibrary.getFunction(NativeLibrary.java:582)
        at com.sun.jna.Library$Handler.invoke(Library.java:248)
        at jdk.proxy2/jdk.proxy2.$Proxy4.getrusage(Unknown Source)
        at hre.perf.ResourceUsage$.get(ResourceUsage.scala:13)
        at hre.perf.ResourceUsage$.getProcess(ResourceUsage.scala:18)
        at hre.progress.TaskRegistry$.ownUsage(TaskRegistry.scala:55)
        at hre.progress.task.AbstractTask.start(AbstractTask.scala:59)
        at hre.progress.TaskRegistry$.install(TaskRegistry.scala:18)
        at hre.progress.Progress$.install(Progress.scala:13)
        at vct.main.Main$.runOptions(Main.scala:78)
        at vct.main.Main$.main(Main.scala:41)
        at vct.main.Main.main(Main.scala)
```
According to @niomaster, `getrusage` is a Linux system call, and thus does not exist on Windows. An alternative solution for the progress printing on Windows should be implemented.

**Comment by niomaster** [comment]
to be nitpicky and precise for posterity: we assume that java is linked against a libc (e.g. glibc: https://www.gnu.org/software/libc/manual/html_node/Resource-Usage.html), which has a function `getrusage`, which fronts the `getrusage` syscall. This is erroneously always done in the static initialization of `hre.unix.Libc`, but should only be done on usage.

**Comment by niomaster** [comment]
Actually ideally we fall back on only reporting wall-time profiling information on windows
